### ISSUE TITLE
Paid app doesn't work after turning on wifi

### ISSUE THREAD

**Issue by Medis2** [t4rra/i-forgor#1]
Hi,

I installed **fl studio mobile** the same way as you explained, but when I create a new project some files need to be installed first inside the app in order to create music, so when I turn on the wifi, the app stops and I cannot click anything anymore, even if turn off the wifi and relaunch fl studio or if restart the pc it wont work. 
If you there are any possible solution don't forget to reply plz :).

Thx.

**Comment by t4rra** [comment]
There's probably a license check or similar when downloading online files so that might be the issue. Unfortunately can't help much here, I haven't used windows in almost a year :/
